image: bitnami/minideb:latest

stages:
  - deploy

deploying:
  variables:
    GIT_STRATEGY: none
  tags:
    - docker
  stage: deploy
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )"
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  script:
    - ssh -tt repocurso@repocursos.saiteava.org "source ~/.profile; /usr/bin/ruby ~/pipeline/resourcePipeline.rb $RESOURCE_PATH \"$RESOURCE_NAME\" $CI_REPOSITORY_URL \"$CI_COMMIT_REF_NAME\""
    - echo "Deploy finished"
  only:
    refs:
      - master
      - develop
